#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

struct mijn_struct {
int i;
float f;
struct mijn_struct* next;
};

struct DS_struct_0 {
float a;
};

struct DS_struct_1 {
unsigned char a;
};

struct DS_struct_2 {
long a;
};

struct DS_struct_3 {
long a;
};

struct DS_struct_4 {
unsigned long a;
};

struct DS_struct_6 {
float a;
};

struct DS_struct_5 {
struct DS_struct_6 a;
};
// function declarations

void functie_voor_datastructuren(struct mijn_struct*);

char FF_function_48701(void);

char FF_function_48702(void);

char FF_function_48703(void);

char FF_function_48704(unsigned short, double, unsigned long long);

char FF_function_48705(void);

char FF_function_48706(long);

char FF_function_48707(unsigned char, float);

char FF_function_48708(long long, unsigned char, short);

char FF_function_48709(unsigned short, short, unsigned char);

char FF_function_48710(double, short, unsigned short);

char FF_function_48712(long long, ...);

long long FF_function_48714(struct mijn_struct, ...);

struct mijn_struct FF_function_48716(struct mijn_struct, ...);

long long FF_function_48721(struct mijn_struct, ...);

struct mijn_struct FF_function_48723(struct mijn_struct, ...);

unsigned long FF_function_48726(unsigned long long, ...);

struct DS_struct_1 FF_function_48738(long, ...);

struct DS_struct_1 FF_function_48746(struct DS_struct_0, ...);

struct mijn_struct FF_function_48750(short, ...);

double FF_function_48756(struct mijn_struct, ...);

struct mijn_struct FF_function_48757(long long, double);

char FF_function_48758(long long);

float FF_function_48759(long long, short, char);

double FF_function_48761(unsigned long, ...);

unsigned long FF_function_48763(long long, unsigned long, long);

unsigned long FF_function_48762(long long, unsigned char, unsigned long, long, char);

long long FF_function_48764(void);

unsigned char FF_function_48765(void);

unsigned long FF_function_48766(void);

long FF_function_48767(void);

char FF_function_48768(void);

unsigned long FF_function_48770(void);

unsigned long FF_function_48769(void);

unsigned long long FF_function_48772(void);

unsigned long long FF_function_48771(void);

double FF_function_48754(short, unsigned long long, float, float);

char FF_function_48774(void);

short FF_function_48776(void);

short FF_function_48775(void);

short FF_function_48773(void);

unsigned long long FF_function_48778(void);

unsigned long long FF_function_48780(void);

unsigned long long FF_function_48779(void);

unsigned long long FF_function_48777(void);

char FF_function_48782(void);

float FF_function_48784(unsigned char);

float FF_function_48783(void);

float FF_function_48781(unsigned char, long, long long, long);

unsigned char FF_function_48786(struct DS_struct_1, ...);

struct DS_struct_1 FF_function_48753(unsigned long long);

struct mijn_struct FF_function_48752(float, unsigned long long);

short FF_function_48751(long);

short FF_function_48748(unsigned long, long long, double, long, float, long);

struct DS_struct_0 FF_function_48747(float);

unsigned char FF_function_48744(unsigned short, float, unsigned short);

unsigned long FF_function_48743(long long, long long, char, char, unsigned short);

char FF_function_48742(unsigned long long);

long FF_function_48741(unsigned long long);

unsigned char FF_function_48740(long, unsigned char);

long FF_function_48739(unsigned long long);

char FF_function_48736(unsigned long long, unsigned long);

struct DS_struct_0 FF_function_48735(long, unsigned char, double, unsigned long, float, unsigned long, unsigned short);

struct mijn_struct FF_function_48734(unsigned short, long, float);

unsigned long long FF_function_48733(unsigned short, unsigned long long, double, long long, char, long, short, unsigned char);

char FF_function_48732(char, long long, short);

struct mijn_struct FF_function_48731(float, unsigned short);

long FF_function_48730(short, long, unsigned long);

struct DS_struct_0 FF_function_48729(unsigned long);

struct mijn_struct FF_function_48728(long long, double);

unsigned long long FF_function_48727(unsigned long long, short, long, unsigned long, long);

struct mijn_struct FF_function_48724(unsigned long, unsigned char);

struct mijn_struct FF_function_48719(char);

unsigned short FF_function_48718(unsigned long);

struct mijn_struct FF_function_48717(unsigned long long, long long, long long, unsigned long long, unsigned short, unsigned long long, float, double, float, unsigned char, double);

struct mijn_struct CF_function_48787(long long);

struct DS_struct_4 CF_function_48788(double);
// global variable declarations 

#pragma clang diagnostic ignored "-Wunused-value"

// global variables

// functions

void functie_voor_datastructuren(struct mijn_struct* ptr){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:functie_voor_datastructuren,AUTOGENERATED:T,ID:61209,CHECKSUM:B8BE");
	ptr->i = 0;
	ptr->f = 0;
	ptr->next = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:functie_voor_datastructuren,AUTOGENERATED:T,ID:6120a,CHECKSUM:98A7");
}

char FF_function_48701(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_48701,AUTOGENERATED:T,ID:6120b,CHECKSUM:2FF3");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48701,AUTOGENERATED:T,ID:6120c,CHECKSUM:EDD7");
		return 0;
}

char FF_function_48702(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_48702,AUTOGENERATED:T,ID:6120d,CHECKSUM:6D78");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48702,AUTOGENERATED:T,ID:6120e,CHECKSUM:AF5C");
		return 0;
}

char FF_function_48703(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_48703,AUTOGENERATED:T,ID:6120f,CHECKSUM:5301");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48703,AUTOGENERATED:T,ID:61210,CHECKSUM:FF65");
		return 0;
}

char FF_function_48704(unsigned short p0, double p1, unsigned long long p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_48704,AUTOGENERATED:T,ID:61211,CHECKSUM:42AF");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48704,AUTOGENERATED:T,ID:61212,CHECKSUM:410A");
		return 0;
}

char FF_function_48705(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_48705,AUTOGENERATED:T,ID:61213,CHECKSUM:7CD6");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48705,AUTOGENERATED:T,ID:61214,CHECKSUM:BC72");
		return 0;
}

char FF_function_48706(long p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_48706,AUTOGENERATED:T,ID:61215,CHECKSUM:3E5D");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48706,AUTOGENERATED:T,ID:61216,CHECKSUM:3DF8");
		return 0;
}

char FF_function_48707(unsigned char p0, float p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_48707,AUTOGENERATED:T,ID:61217,CHECKSUM:0024");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48707,AUTOGENERATED:T,ID:61218,CHECKSUM:0681");
		return 0;
}

char FF_function_48708(long long p0, unsigned char p1, short p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_48708,AUTOGENERATED:T,ID:61219,CHECKSUM:C481");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48708,AUTOGENERATED:T,ID:6121a,CHECKSUM:3C65");
		return 0;
}

char FF_function_48709(unsigned short p0, short p1, unsigned char p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_48709,AUTOGENERATED:T,ID:6121b,CHECKSUM:C038");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48709,AUTOGENERATED:T,ID:6121c,CHECKSUM:021C");
		return 0;
}

char FF_function_48710(double p0, short p1, unsigned short p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_48710,AUTOGENERATED:T,ID:6121d,CHECKSUM:C074");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48710,AUTOGENERATED:T,ID:6121e,CHECKSUM:0250");
		return 0;
}

char FF_function_48712(long long p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48712,AUTOGENERATED:T,ID:6121f,CHECKSUM:FD39");
	va_list va;
	va_start(va, p1);
	char first = __builtin_va_arg(va, char);
	va_end(va);
	FF_function_48712(0,1);
	FF_function_48712(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48712,AUTOGENERATED:T,ID:61220,CHECKSUM:7263");
	return first;
}

long long FF_function_48714(struct mijn_struct p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48714,AUTOGENERATED:T,ID:61221,CHECKSUM:736E");
	va_list va;
	va_start(va, p1);
	long long first = __builtin_va_arg(va, long long);
	va_end(va);
	FF_function_48714((struct mijn_struct){0, 0.5, 0},1);
	FF_function_48714((struct mijn_struct){0, 0.5, 0},1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48714,AUTOGENERATED:T,ID:61222,CHECKSUM:33F4");
	return first;
}

struct mijn_struct FF_function_48716(struct mijn_struct p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48716,AUTOGENERATED:T,ID:61223,CHECKSUM:0D1C");
	va_list va;
	va_start(va, p1);
	struct mijn_struct first = __builtin_va_arg(va, struct mijn_struct);
	va_end(va);
	FF_function_48716((struct mijn_struct){0, 0.5, 0},1);
	FF_function_48716((struct mijn_struct){0, 0.5, 0},1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48716,AUTOGENERATED:T,ID:61224,CHECKSUM:8E87");
	return first;
}

long long FF_function_48721(struct mijn_struct p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48721,AUTOGENERATED:T,ID:61225,CHECKSUM:B773");
	va_list va;
	va_start(va, p1);
	long long first = __builtin_va_arg(va, long long);
	va_end(va);
	FF_function_48721((struct mijn_struct){0, 0.5, 0},1);
	FF_function_48721((struct mijn_struct){0, 0.5, 0},1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48721,AUTOGENERATED:T,ID:61226,CHECKSUM:F7E9");
	return first;
}

struct mijn_struct FF_function_48723(struct mijn_struct p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48723,AUTOGENERATED:T,ID:61227,CHECKSUM:C901");
	va_list va;
	va_start(va, p1);
	struct mijn_struct first = __builtin_va_arg(va, struct mijn_struct);
	va_end(va);
	FF_function_48723((struct mijn_struct){0, 0.5, 0},1);
	FF_function_48723((struct mijn_struct){0, 0.5, 0},1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48723,AUTOGENERATED:T,ID:61228,CHECKSUM:8C9B");
	return first;
}

unsigned long FF_function_48726(unsigned long long p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48726,AUTOGENERATED:T,ID:61229,CHECKSUM:CD9D");
	va_list va;
	va_start(va, p1);
	unsigned long first = __builtin_va_arg(va, unsigned long);
	va_end(va);
	FF_function_48726(0,1);
	FF_function_48726(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48726,AUTOGENERATED:T,ID:6122a,CHECKSUM:7646");
	return first;
}

struct DS_struct_1 FF_function_48738(long p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48738,AUTOGENERATED:T,ID:6122b,CHECKSUM:4BFE");
	va_list va;
	va_start(va, p1);
	struct DS_struct_1 first = __builtin_va_arg(va, struct DS_struct_1);
	va_end(va);
	FF_function_48738(0,1);
	FF_function_48738(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48738,AUTOGENERATED:T,ID:6122c,CHECKSUM:CAE5");
	return first;
}

struct DS_struct_1 FF_function_48746(struct DS_struct_0 p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48746,AUTOGENERATED:T,ID:6122d,CHECKSUM:FA5D");
	va_list va;
	va_start(va, p1);
	struct DS_struct_1 first = __builtin_va_arg(va, struct DS_struct_1);
	va_end(va);
	FF_function_48746((struct DS_struct_0){0.0},1);
	FF_function_48746((struct DS_struct_0){0.0},1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48746,AUTOGENERATED:T,ID:6122e,CHECKSUM:7B46");
	return first;
}

struct mijn_struct FF_function_48750(short p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48750,AUTOGENERATED:T,ID:6122f,CHECKSUM:3934");
	va_list va;
	va_start(va, p1);
	struct mijn_struct first = __builtin_va_arg(va, struct mijn_struct);
	va_end(va);
	FF_function_48750(0,1);
	FF_function_48750(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48750,AUTOGENERATED:T,ID:61230,CHECKSUM:D66F");
	return first;
}

double FF_function_48756(struct mijn_struct p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48756,AUTOGENERATED:T,ID:61231,CHECKSUM:D762");
	va_list va;
	va_start(va, p1);
	double first = __builtin_va_arg(va, double);
	va_end(va);
	FF_function_48756((struct mijn_struct){0, 0.5, 0},1);
	FF_function_48756((struct mijn_struct){0, 0.5, 0},1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48756,AUTOGENERATED:T,ID:61232,CHECKSUM:97F8");
	return first;
}

struct mijn_struct FF_function_48757(long long p0, double p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48757,AUTOGENERATED:T,ID:61233,CHECKSUM:E91B");
	0;
	if (rand() < 1) {
		return (struct mijn_struct){0, 0.5, 0};
	}
	(struct DS_struct_0){0.0};
	if (rand() < 1) {
		return (struct mijn_struct){0, 0.5, 0};
	}
	(struct DS_struct_0){0.0};
	if (rand() < 1) {
		return (struct mijn_struct){0, 0.5, 0};
	}
	0;
	if (rand() < 1) {
		return (struct mijn_struct){0, 0.5, 0};
	}
	(struct DS_struct_1){0};
	if (rand() < 1) {
		return (struct mijn_struct){0, 0.5, 0};
	}
	0.0;
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48757,AUTOGENERATED:T,ID:61234,CHECKSUM:6A80");
	return FF_x;
}

char FF_function_48758(long long p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48758,AUTOGENERATED:T,ID:61235,CHECKSUM:EBBF");
	(struct DS_struct_1){0};
	if (rand() < 1) {
		return 0;
	}
	(struct DS_struct_1){0};
	if (rand() < 1) {
		return 0;
	}
	(struct DS_struct_0){0.0};
	if (rand() < 1) {
		return 0;
	}
	(struct DS_struct_0){0.0};
		return 0;
	(struct DS_struct_2){0};
		return 0;
	0;
	char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48758,AUTOGENERATED:T,ID:61236,CHECKSUM:AB25");
	return FF_x;
}

float FF_function_48759(long long p0, short p1, char p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48759,AUTOGENERATED:T,ID:61237,CHECKSUM:D5C6");
	(struct DS_struct_0){0.0};
		return 0.0;
	(struct DS_struct_1){0};
	if (rand() < 1) {
		return 0.0;
	}
	(struct DS_struct_2){0};
		return 0.0;
	0.0;
		return 0.0;
	0;
	if (rand() < 1) {
		return 0.0;
	}
	0;
	float FF_x = 0.0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48759,AUTOGENERATED:T,ID:61238,CHECKSUM:905C");
	return FF_x;
}

double FF_function_48761(unsigned long p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48761,AUTOGENERATED:T,ID:61239,CHECKSUM:A98C");
	va_list va;
	va_start(va, p1);
	double first = __builtin_va_arg(va, double);
	va_end(va);
	FF_function_48761(0,1);
	FF_function_48761(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48761,AUTOGENERATED:T,ID:6123a,CHECKSUM:1257");
	return first;
}

unsigned long FF_function_48763(long long p0, unsigned long p1, long p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48763,AUTOGENERATED:T,ID:6123b,CHECKSUM:ED3E");
	(struct DS_struct_1){0};
	unsigned long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48763,AUTOGENERATED:T,ID:6123c,CHECKSUM:6C25");
	return FF_x;
}

unsigned long FF_function_48762(long long p0, unsigned char p1, unsigned long p2, long p3, char p4){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48762,AUTOGENERATED:T,ID:6123d,CHECKSUM:1046");
	0;
	unsigned long FF_x = FF_function_48763(0, 0, 0);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48762,AUTOGENERATED:T,ID:6123e,CHECKSUM:915D");
	return FF_x;
}

long long FF_function_48764(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48764,AUTOGENERATED:T,ID:6123f,CHECKSUM:51D1");
	0;
	long long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48764,AUTOGENERATED:T,ID:61240,CHECKSUM:1E89");
	return FF_x;
}

unsigned char FF_function_48765(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48765,AUTOGENERATED:T,ID:61241,CHECKSUM:606A");
	0;
	unsigned char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48765,AUTOGENERATED:T,ID:61242,CHECKSUM:20F0");
	return FF_x;
}

unsigned long FF_function_48766(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48766,AUTOGENERATED:T,ID:61243,CHECKSUM:E1E0");
	(struct mijn_struct){0, 0.5, 0};
	unsigned long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48766,AUTOGENERATED:T,ID:61244,CHECKSUM:627B");
	return FF_x;
}

long FF_function_48767(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48767,AUTOGENERATED:T,ID:61245,CHECKSUM:1C98");
	(struct mijn_struct){0, 0.5, 0};
	if (rand() < 1) {
		return 0;
	}
	0.0;
	long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48767,AUTOGENERATED:T,ID:61246,CHECKSUM:5C02");
	return FF_x;
}

char FF_function_48768(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48768,AUTOGENERATED:T,ID:61247,CHECKSUM:DD3D");
	(struct DS_struct_1){0};
	char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48768,AUTOGENERATED:T,ID:61248,CHECKSUM:98A7");
	return FF_x;
}

unsigned long FF_function_48770(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48770,AUTOGENERATED:T,ID:61249,CHECKSUM:E488");
	0;
	unsigned long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48770,AUTOGENERATED:T,ID:6124a,CHECKSUM:5F53");
	return FF_x;
}

unsigned long FF_function_48769(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48769,AUTOGENERATED:T,ID:6124b,CHECKSUM:1D05");
	0;
	unsigned long FF_x = FF_function_48770();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48769,AUTOGENERATED:T,ID:6124c,CHECKSUM:9C1E");
	return FF_x;
}

unsigned long long FF_function_48772(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48772,AUTOGENERATED:T,ID:6124d,CHECKSUM:A2BA");
	0;
	unsigned long long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48772,AUTOGENERATED:T,ID:6124e,CHECKSUM:23A1");
	return FF_x;
}

unsigned long long FF_function_48771(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48771,AUTOGENERATED:T,ID:6124f,CHECKSUM:2330");
	(struct DS_struct_2){0};
		return 0;
	(struct DS_struct_1){0};
	unsigned long long FF_x = FF_function_48772();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48771,AUTOGENERATED:T,ID:61250,CHECKSUM:CC6B");
	return FF_x;
}

double FF_function_48754(short p0, unsigned long long p1, float p2, float p3){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48754,AUTOGENERATED:T,ID:61251,CHECKSUM:C892");
	FF_function_48756(FF_function_48757(0, 0.0), FF_function_48758(0), FF_function_48759(0, 0, 0));
	double FF_x = FF_function_48761(FF_function_48762(FF_function_48764(), FF_function_48765(), FF_function_48766(), FF_function_48767(), FF_function_48768()), FF_function_48769(), FF_function_48771());
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48754,AUTOGENERATED:T,ID:61252,CHECKSUM:8808");
	return FF_x;
}

char FF_function_48774(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48774,AUTOGENERATED:T,ID:61253,CHECKSUM:4CEC");
	(struct DS_struct_2){0};
	char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48774,AUTOGENERATED:T,ID:61254,CHECKSUM:CF77");
	return FF_x;
}

short FF_function_48776(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48776,AUTOGENERATED:T,ID:61255,CHECKSUM:F19F");
	(struct mijn_struct){0, 0.5, 0};
	short FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48776,AUTOGENERATED:T,ID:61256,CHECKSUM:B105");
	return FF_x;
}

short FF_function_48775(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48775,AUTOGENERATED:T,ID:61257,CHECKSUM:7015");
	(struct DS_struct_0){0.0};
	short FF_x = FF_function_48776();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48775,AUTOGENERATED:T,ID:61258,CHECKSUM:358F");
	return FF_x;
}

short FF_function_48773(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48773,AUTOGENERATED:T,ID:61259,CHECKSUM:3482");
	FF_function_48774();
	short FF_x = FF_function_48775();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48773,AUTOGENERATED:T,ID:6125a,CHECKSUM:8F59");
	return FF_x;
}

unsigned long long FF_function_48778(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48778,AUTOGENERATED:T,ID:6125b,CHECKSUM:F002");
	0.0;
	unsigned long long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48778,AUTOGENERATED:T,ID:6125c,CHECKSUM:7119");
	return FF_x;
}

unsigned long long FF_function_48780(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48780,AUTOGENERATED:T,ID:6125d,CHECKSUM:9648");
	(struct mijn_struct){0, 0.5, 0};
	unsigned long long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48780,AUTOGENERATED:T,ID:6125e,CHECKSUM:1753");
	return FF_x;
}

unsigned long long FF_function_48779(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48779,AUTOGENERATED:T,ID:6125f,CHECKSUM:CCFB");
	0;
	unsigned long long FF_x = FF_function_48780();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48779,AUTOGENERATED:T,ID:61260,CHECKSUM:43A1");
	return FF_x;
}

unsigned long long FF_function_48777(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48777,AUTOGENERATED:T,ID:61261,CHECKSUM:3D66");
	FF_function_48778();
	unsigned long long FF_x = FF_function_48779();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48777,AUTOGENERATED:T,ID:61262,CHECKSUM:7DFC");
	return FF_x;
}

char FF_function_48782(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48782,AUTOGENERATED:T,ID:61263,CHECKSUM:27FA");
	(struct DS_struct_3){0};
	char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48782,AUTOGENERATED:T,ID:61264,CHECKSUM:A461");
	return FF_x;
}

float FF_function_48784(unsigned char p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48784,AUTOGENERATED:T,ID:61265,CHECKSUM:A56C");
	(struct DS_struct_3){0};
	float FF_x = 0.0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48784,AUTOGENERATED:T,ID:61266,CHECKSUM:E5F6");
	return FF_x;
}

float FF_function_48783(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48783,AUTOGENERATED:T,ID:61267,CHECKSUM:1B03");
	(struct mijn_struct){0, 0.5, 0};
		return 0.0;
	(struct mijn_struct){0, 0.5, 0};
	float FF_x = FF_function_48784(0);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48783,AUTOGENERATED:T,ID:61268,CHECKSUM:5E99");
	return FF_x;
}

float FF_function_48781(unsigned char p0, long p1, long long p2, long p3){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48781,AUTOGENERATED:T,ID:61269,CHECKSUM:6071");
	FF_function_48782();
	float FF_x = FF_function_48783();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48781,AUTOGENERATED:T,ID:6126a,CHECKSUM:DBAA");
	return FF_x;
}

unsigned char FF_function_48786(struct DS_struct_1 p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48786,AUTOGENERATED:T,ID:6126b,CHECKSUM:E4DE");
	va_list va;
	va_start(va, p1);
	unsigned char first = __builtin_va_arg(va, unsigned char);
	va_end(va);
	FF_function_48786((struct DS_struct_1){0},1);
	FF_function_48786((struct DS_struct_1){0},1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48786,AUTOGENERATED:T,ID:6126c,CHECKSUM:65C5");
	return first;
}

struct DS_struct_1 FF_function_48753(unsigned long long p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48753,AUTOGENERATED:T,ID:6126d,CHECKSUM:78BC");
	FF_function_48754(FF_function_48773(), FF_function_48777(), FF_function_48781(FF_function_48786((struct DS_struct_1){0}, 0, 0), 0, 0, 0), 0.0);
	struct DS_struct_1 FF_x = (struct DS_struct_1){0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48753,AUTOGENERATED:T,ID:6126e,CHECKSUM:F9A7");
	return FF_x;
}

struct mijn_struct FF_function_48752(float p0, unsigned long long p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48752,AUTOGENERATED:T,ID:6126f,CHECKSUM:46C5");
	FF_function_48753(0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48752,AUTOGENERATED:T,ID:61270,CHECKSUM:A99E");
	return FF_x;
}

short FF_function_48751(long p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48751,AUTOGENERATED:T,ID:61271,CHECKSUM:688E");
	FF_function_48752(0.0, 0);
		return 0;
	0;
	short FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48751,AUTOGENERATED:T,ID:61272,CHECKSUM:2814");
	return FF_x;
}

short FF_function_48748(unsigned long p0, long long p1, double p2, long p3, float p4, long p5){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48748,AUTOGENERATED:T,ID:61273,CHECKSUM:ABC3");
	FF_function_48750(FF_function_48751(0), 0.0, 0);
	short FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48748,AUTOGENERATED:T,ID:61274,CHECKSUM:2858");
	return FF_x;
}

struct DS_struct_0 FF_function_48747(float p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48747,AUTOGENERATED:T,ID:61275,CHECKSUM:A967");
	FF_function_48748(0, 0, 0.0, 0, 0.0, 0);
		return (struct DS_struct_0){0.0};
	(struct DS_struct_2){0};
	struct DS_struct_0 FF_x = (struct DS_struct_0){0.0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48747,AUTOGENERATED:T,ID:61276,CHECKSUM:E9FD");
	return FF_x;
}

unsigned char FF_function_48744(unsigned short p0, float p1, unsigned short p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48744,AUTOGENERATED:T,ID:61277,CHECKSUM:28ED");
	FF_function_48746(FF_function_48747(0.0), 0, 0);
	unsigned char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48744,AUTOGENERATED:T,ID:61278,CHECKSUM:6D77");
	return FF_x;
}

unsigned long FF_function_48743(long long p0, long long p1, char p2, char p3, unsigned short p4){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48743,AUTOGENERATED:T,ID:61279,CHECKSUM:9382");
	FF_function_48744(0, 0.0, 0);
	unsigned long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48743,AUTOGENERATED:T,ID:6127a,CHECKSUM:2859");
	return FF_x;
}

char FF_function_48742(unsigned long long p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48742,AUTOGENERATED:T,ID:6127b,CHECKSUM:973B");
	FF_function_48743(0, 0, 0, 0, 0);
	char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48742,AUTOGENERATED:T,ID:6127c,CHECKSUM:1620");
	return FF_x;
}

long FF_function_48741(unsigned long long p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48741,AUTOGENERATED:T,ID:6127d,CHECKSUM:D5B0");
	FF_function_48742(0);
	long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48741,AUTOGENERATED:T,ID:6127e,CHECKSUM:54AB");
	return FF_x;
}

unsigned char FF_function_48740(long p0, unsigned char p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48740,AUTOGENERATED:T,ID:6127f,CHECKSUM:EBC9");
	FF_function_48741(0);
	unsigned char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48740,AUTOGENERATED:T,ID:61280,CHECKSUM:6496");
	return FF_x;
}

long FF_function_48739(unsigned long long p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48739,AUTOGENERATED:T,ID:61281,CHECKSUM:2940");
	FF_function_48740(0, 0);
		return 0;
	0;
	long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48739,AUTOGENERATED:T,ID:61282,CHECKSUM:69DA");
	return FF_x;
}

char FF_function_48736(unsigned long long p0, unsigned long p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48736,AUTOGENERATED:T,ID:61283,CHECKSUM:E8E5");
	FF_function_48738(FF_function_48739(0), 0, 0);
	char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48736,AUTOGENERATED:T,ID:61284,CHECKSUM:6B7E");
	return FF_x;
}

struct DS_struct_0 FF_function_48735(long p0, unsigned char p1, double p2, unsigned long p3, float p4, unsigned long p5, unsigned short p6){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48735,AUTOGENERATED:T,ID:61285,CHECKSUM:AA6E");
	FF_function_48736(0, 0);
		return (struct DS_struct_0){0.0};
	0;
	if (rand() < 1) {
		return (struct DS_struct_0){0.0};
	}
	(struct DS_struct_0){0.0};
	struct DS_struct_0 FF_x = (struct DS_struct_0){0.0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48735,AUTOGENERATED:T,ID:61286,CHECKSUM:EAF4");
	return FF_x;
}

struct mijn_struct FF_function_48734(unsigned short p0, long p1, float p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48734,AUTOGENERATED:T,ID:61287,CHECKSUM:9417");
	FF_function_48735(0, 0, 0.0, 0, 0.0, 0, 0);
		return (struct mijn_struct){0, 0.5, 0};
	(struct DS_struct_4){0};
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48734,AUTOGENERATED:T,ID:61288,CHECKSUM:D18D");
	return FF_x;
}

unsigned long long FF_function_48733(unsigned short p0, unsigned long long p1, double p2, long long p3, char p4, long p5, short p6, unsigned char p7){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48733,AUTOGENERATED:T,ID:61289,CHECKSUM:2F78");
	FF_function_48734(0, 0, 0.0);
	unsigned long long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48733,AUTOGENERATED:T,ID:6128a,CHECKSUM:94A3");
	return FF_x;
}

char FF_function_48732(char p0, long long p1, short p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48732,AUTOGENERATED:T,ID:6128b,CHECKSUM:2BC1");
	FF_function_48733(0, 0, 0.0, 0, 0, 0, 0, 0);
	char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48732,AUTOGENERATED:T,ID:6128c,CHECKSUM:AADA");
	return FF_x;
}

struct mijn_struct FF_function_48731(float p0, unsigned short p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48731,AUTOGENERATED:T,ID:6128d,CHECKSUM:694A");
	FF_function_48732(0, 0, 0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48731,AUTOGENERATED:T,ID:6128e,CHECKSUM:E851");
	return FF_x;
}

long FF_function_48730(short p0, long p1, unsigned long p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48730,AUTOGENERATED:T,ID:6128f,CHECKSUM:5733");
	FF_function_48731(0.0, 0);
	long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48730,AUTOGENERATED:T,ID:61290,CHECKSUM:B868");
	return FF_x;
}

struct DS_struct_0 FF_function_48729(unsigned long p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48729,AUTOGENERATED:T,ID:61291,CHECKSUM:3BBF");
	FF_function_48730(0, 0, 0);
	struct DS_struct_0 FF_x = (struct DS_struct_0){0.0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48729,AUTOGENERATED:T,ID:61292,CHECKSUM:7B25");
	return FF_x;
}

struct mijn_struct FF_function_48728(long long p0, double p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48728,AUTOGENERATED:T,ID:61293,CHECKSUM:05C6");
	FF_function_48729(0);
		return (struct mijn_struct){0, 0.5, 0};
	(struct DS_struct_2){0};
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48728,AUTOGENERATED:T,ID:61294,CHECKSUM:865D");
	return FF_x;
}

unsigned long long FF_function_48727(unsigned long long p0, short p1, long p2, unsigned long p3, long p4){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48727,AUTOGENERATED:T,ID:61295,CHECKSUM:0762");
	FF_function_48728(0, 0.0);
		return 0;
	(struct DS_struct_5){(struct DS_struct_6){0.0}};
	if (rand() < 1) {
		return 0;
	}
	(struct DS_struct_5){(struct DS_struct_6){0.0}};
	if (rand() < 1) {
		return 0;
	}
	0;
		return 0;
	0;
	unsigned long long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48727,AUTOGENERATED:T,ID:61296,CHECKSUM:47F8");
	return FF_x;
}

struct mijn_struct FF_function_48724(unsigned long p0, unsigned char p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48724,AUTOGENERATED:T,ID:61297,CHECKSUM:86E8");
	FF_function_48726(FF_function_48727(0, 0, 0, 0, 0), 0, 0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48724,AUTOGENERATED:T,ID:61298,CHECKSUM:C372");
	return FF_x;
}

struct mijn_struct FF_function_48719(char p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48719,AUTOGENERATED:T,ID:61299,CHECKSUM:3ABF");
	FF_function_48721(FF_function_48723(FF_function_48724(0, 0), 0, 0.0), 0, 0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48719,AUTOGENERATED:T,ID:6129a,CHECKSUM:8164");
	return FF_x;
}

unsigned short FF_function_48718(unsigned long p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48718,AUTOGENERATED:T,ID:6129b,CHECKSUM:3E06");
	FF_function_48719(0);
	unsigned short FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48718,AUTOGENERATED:T,ID:6129c,CHECKSUM:BF1D");
	return FF_x;
}

struct mijn_struct FF_function_48717(unsigned long long p0, long long p1, long long p2, unsigned long long p3, unsigned short p4, unsigned long long p5, float p6, double p7, float p8, unsigned char p9, double p10){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_48717,AUTOGENERATED:T,ID:6129d,CHECKSUM:3CA2");
	FF_function_48718(0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_48717,AUTOGENERATED:T,ID:6129e,CHECKSUM:BDB9");
	return FF_x;
}

struct mijn_struct CF_function_48787(long long p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:CF_function_48787,AUTOGENERATED:T,ID:6129f,CHECKSUM:212B");
	/* I/F TYPE    N/U IN UP TS  IC IE  EB EE ER ED EN EF  LV VT LU LT */
	/* PFL DOWHILE --  T  T  F   T  F   T  T  F  T  F  T   T  F  +? xx  */
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LVN:CF_LV94817,EGF:T,loopcom:DOWHILE,ICC:T,LVT:FLOAT,LOOPID:94817,INEXP:3.65,UPEXP:+=getchar(),PLID:-1,EBR:T,NESTLEV:0,UNR:NU,finitude:PFL,EEX:T,location:BEFORE,ID:611d6,EGA:T,CHECKSUM:7A2C");
	float CF_LV94817=3.65; /* loop var init */
	do {
		printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94817,location:BODY,__FLOAT_FIELD__:%f,ID:611d7,CHECKSUM:DA8E", CF_LV94817);
		printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94817,location:UNDEFINED,ID:611d8,DUMMY:T,CHECKSUM:FF66");
		if (getchar()==23) {break;}
		if (getchar()==97) {exit(1923);}
		if (getchar()==19) {goto _LAB4;} // goto directly after
		if (getchar()==83) {
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94817,location:BEFORE_GOTO_FURTHER_AFTER,ID:611d9,CHECKSUM:1EB8");
			goto _LAB5; // goto further after
		}
		printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94817,location:UNDEFINED,ID:611da,DUMMY:T,CHECKSUM:ACF0");
		/* I/F TYPE    N/U IN UP TS  IC IE  EB EE ER ED EN EF  LV VT LU LT */
		/* PFL DOWHILE --  F  F  F   T  T   T  F  F  T  T  T   F           */
		printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>EGF:T,loopcom:DOWHILE,IGE:T,ICC:T,LOOPID:94818,EBM:T,PLID:94817,EBR:T,NESTLEV:1,UNR:NU,finitude:PFL,location:BEFORE,ID:611db,EGA:T,CHECKSUM:4C14");
		/* no loop var used, so no init */
		do {
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94818,location:BODY,ID:611dc,CHECKSUM:FCCC");
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94818,location:UNDEFINED,ID:611dd,DUMMY:T,CHECKSUM:0C71");
			if (getchar()==23) {break;}
			if (getchar()==19) {goto _LAB7;} // goto directly after
			if (getchar()==83) {
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94818,location:BEFORE_GOTO_FURTHER_AFTER,ID:611de,CHECKSUM:D0C2");
				goto _LAB8; // goto further after
			}
			if (getchar()==73) {
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94818,location:BEFORE_GOTO_BREAK_MULTIPLE,ID:611df,CHECKSUM:4482");
				goto _LAB4; // goto end of root loop
			}
			FF_function_48733(0, 0, 0.0, 0, 0, 0, 0, 0);
			if (getchar()==67) {continue;}
			if (getchar()==17) {goto _LAB6;} // goto end of loop body
			FF_function_48773();
			_LAB6:
			;
		} while (true);
		_LAB7:
		printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94818,location:AFTER,ID:611e0,CHECKSUM:4A45");
		printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94818,location:UNDEFINED,ID:611e1,DUMMY:T,CHECKSUM:9AE3");
		_LAB8:
		;
		if (getchar()==67) {continue;}
		printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94817,location:UNDEFINED,ID:611e2,DUMMY:T,CHECKSUM:9A49");
		_LAB3:
		CF_LV94817+=getchar();
	} while (true);
	_LAB4:
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94817,location:AFTER,ID:611e3,CHECKSUM:6F05");
	FF_function_48766();
	_LAB5:
	;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:CF_function_48787,AUTOGENERATED:T,ID:612a0,CHECKSUM:9E4A");
	return (struct mijn_struct){0, 0.5, 0};
}

struct DS_struct_4 CF_function_48788(double p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:CF_function_48788,AUTOGENERATED:T,ID:612a1,CHECKSUM:1F75");
	if (getchar()==79) {
		/* I/F TYPE    N/U IN UP TS  IC IE  EB EE ER ED EN EF  LV VT LU LT */
		/* TIL FOR     --  T  T  F   F  F   F  F  F  F  F  F   T  I  ++ xx  */
		printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94825,INEXP:4,UPEXP:++,PLID:-1,LVN:CF_LV94825,loopcom:FOR,NESTLEV:0,UNR:NU,finitude:TIL,location:BEFORE,ID:611eb,LVT:INT,CHECKSUM:62A1");
		/* for is not initialized separately */
		for (int CF_LV94825=4;;CF_LV94825++) {
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94825,location:BODY,ID:611ec,__DECIMAL_FIELD__:%d,CHECKSUM:5BD4", CF_LV94825);
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94825,location:UNDEFINED,ID:611ed,DUMMY:T,CHECKSUM:4315");
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94825,location:UNDEFINED,ID:611ee,DUMMY:T,CHECKSUM:D318");
			/* I/F TYPE    N/U IN UP TS  IC IE  EB EE ER ED EN EF  LV VT LU LT */
			/* PFL WHILE   --  T  T  T   T  F   F  T  T  T  F  F   T  I  += !=  */
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LVN:CF_LV94823,loopcom:WHILE,ICC:T,LVT:INT,LOOPID:94823,INEXP:3,UPEXP:+=11,PLID:94825,NESTLEV:1,TSEXP:!=8859,UNR:NU,finitude:PFL,EEX:T,location:BEFORE,ID:611ef,EXR:T,EGA:T,CHECKSUM:421F");
			int CF_LV94823=3; /* loop var init */
			while (CF_LV94823!=8859) {
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94823,location:BODY,ID:611f0,__DECIMAL_FIELD__:%d,CHECKSUM:31C3", CF_LV94823);
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94823,location:UNDEFINED,ID:611f1,DUMMY:T,CHECKSUM:BF6B");
				if (getchar()==97) {exit(1923);}
				if (getchar()==31) {struct DS_struct_4 out; return out;}
				if (getchar()==19) {goto _LAB13;} // goto directly after
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94823,location:UNDEFINED,ID:611f2,DUMMY:T,CHECKSUM:4F7F");
				/* I/F TYPE    N/U IN UP TS  IC IE  EB EE ER ED EN EF  LV VT LU LT */
				/* PFL WHILE   --  T  T  T   T  F   F  F  F  T  T  T   T  F  -- >   */
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LVN:CF_LV94824,EGF:T,loopcom:WHILE,ICC:T,LVT:FLOAT,LOOPID:94824,INEXP:6770.07,UPEXP:--,EBM:T,PLID:94823,NESTLEV:2,TSEXP:>8,UNR:NU,finitude:PFL,location:BEFORE,ID:611f3,EGA:T,CHECKSUM:FF9D");
				float CF_LV94824=6770.07; /* loop var init */
				while (CF_LV94824>8) {
					printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94824,location:BODY,__FLOAT_FIELD__:%f,ID:611f4,CHECKSUM:8BCA", CF_LV94824);
					printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94824,location:UNDEFINED,ID:611f5,DUMMY:T,CHECKSUM:4F08");
					if (getchar()==19) {goto _LAB16;} // goto directly after
					if (getchar()==83) {
						printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94824,location:BEFORE_GOTO_FURTHER_AFTER,ID:611f6,CHECKSUM:3EFA");
						goto _LAB17; // goto further after
					}
					if (getchar()==73) {
						printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94824,location:BEFORE_GOTO_BREAK_MULTIPLE,ID:611f7,CHECKSUM:3A30");
						goto _LAB10; // goto end of root loop
					}
					FF_function_48774();
					if (getchar()==67) {continue;}
					printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94824,location:UNDEFINED,ID:611f8,DUMMY:T,CHECKSUM:DF50");
					_LAB15:
					CF_LV94824--;
				}
				_LAB16:
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94824,location:AFTER,ID:611f9,CHECKSUM:9371");
				FF_function_48764();
				_LAB17:
				;
				/* I/F TYPE    N/U IN UP TS  IC IE  EB EE ER ED EN EF  LV VT LU LT */
				/* PFL FOR     UU+ T  T  T   F  F   F  F  F  F  F  F   T  F  += <=  */
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LVN:CF_LV94822,loopcom:FOR,LVT:FLOAT,LOOPID:94822,INEXP:2024.67,UPEXP:+=3.36,PLID:94823,UNRIT:10,NESTLEV:2,TSEXP:<=2057.6,UNR:U+,finitude:PFL,location:BEFORE,ID:611fa,CHECKSUM:1793");
				/* for is not initialized separately */
				for (float CF_LV94822=2024.67;CF_LV94822<=2057.6;CF_LV94822+=3.36) {
					printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94822,location:BODY,__FLOAT_FIELD__:%f,ID:611fb,CHECKSUM:71C5", CF_LV94822);
					getchar();
					_LAB18:
					;
				}
				_LAB19:
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94822,location:AFTER,ID:611fc,CHECKSUM:3F0F");
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94822,location:UNDEFINED,ID:611fd,DUMMY:T,CHECKSUM:7CB4");
				FF_function_48777();
				FF_function_48761(0);
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94822,location:UNDEFINED,ID:611fe,DUMMY:T,CHECKSUM:ECB9");
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94822,location:UNDEFINED,ID:611ff,DUMMY:T,CHECKSUM:1CAD");
				FF_function_48743(0, 0, 0, 0, 0);
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94822,location:UNDEFINED,ID:61200,DUMMY:T,CHECKSUM:A596");
				FF_function_48751(0);
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94822,location:UNDEFINED,ID:61201,DUMMY:T,CHECKSUM:359B");
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94822,location:UNDEFINED,ID:61202,DUMMY:T,CHECKSUM:C58F");
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94822,location:UNDEFINED,ID:61203,DUMMY:T,CHECKSUM:5582");
				_LAB20:
				;
				if (getchar()==67) {continue;}
				printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94823,location:UNDEFINED,ID:61204,DUMMY:T,CHECKSUM:F5B8");
				_LAB12:
				CF_LV94823+=11;
			}
			_LAB13:
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94823,location:AFTER,ID:61205,CHECKSUM:5814");
			FF_function_48762(FF_function_48764(), 0, 0, 0, 0);
			_LAB14:
			;
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94825,location:UNDEFINED,ID:61206,DUMMY:T,CHECKSUM:35EC");
			_LAB9:
			;
		}
	}
	_LAB10:
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94825,location:AFTER,ID:61207,CHECKSUM:0E6B");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94825,location:UNDEFINED,ID:61208,DUMMY:T,CHECKSUM:55A0");
	_LAB11:
	;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:CF_function_48788,AUTOGENERATED:T,ID:612a2,CHECKSUM:5FEF");
	return (struct DS_struct_4){0};
}

int main(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:main,AUTOGENERATED:T,ID:612a3,CHECKSUM:D607");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8MD>>ID:611cc,version:1.0.0,CHECKSUM:5BBE");
	struct mijn_struct* my_instance;
	functie_voor_datastructuren(my_instance);
	FF_function_48712(FF_function_48714(FF_function_48716(FF_function_48717(0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0, 0.0), 0, 0), 0, 0));
	(struct DS_struct_6){0.0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:611cd,CHECKSUM:01AF");
	0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:611ce,CHECKSUM:C16E");
	0;
	0;
	0;
	FF_function_48773();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:611cf,CHECKSUM:C02E");
	(struct DS_struct_3){0};
	(struct DS_struct_6){0.0};
	0;
	if (getchar()==79) {
		/* I/F TYPE    N/U IN UP TS  IC IE  EB EE ER ED EN EF  LV VT LU LT */
		/* TIL FOR     --  F  F  F   F  T   F  F  F  F  F  F   F           */
		printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94814,PLID:-1,loopcom:FOR,IGE:T,NESTLEV:0,UNR:NU,finitude:TIL,location:BEFORE,ID:611d0,CHECKSUM:8F0D");
		/* for is not initialized separately */
		for (;;) {
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94814,location:BODY,ID:611d1,CHECKSUM:3ED8");
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94814,location:UNDEFINED,ID:611d2,DUMMY:T,CHECKSUM:AF3F");
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94814,location:UNDEFINED,ID:611d3,DUMMY:T,CHECKSUM:3F32");
			if (getchar()==17) {goto _LAB0;} // goto end of loop body
			printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94814,location:UNDEFINED,ID:611d4,DUMMY:T,CHECKSUM:0F14");
			_LAB0:
			;
		}
	}
	_LAB1:
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:94814,location:AFTER,ID:611d5,CHECKSUM:B67B");
	FF_function_48714(CF_function_48787(0));
	_LAB2:
	;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:611e4,CHECKSUM:9DAC");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:611e5,CHECKSUM:5D6D");
	FF_function_48736(0, 0);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:611e6,CHECKSUM:5C2D");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:611e7,CHECKSUM:9CEC");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:611e8,CHECKSUM:98AC");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:611e9,CHECKSUM:586D");
	0.0;
	0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:611ea,CHECKSUM:A26C");
	CF_function_48788(0.0);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:main,AUTOGENERATED:T,ID:612a4,CHECKSUM:AD25");
	return 0;
}
