#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

struct mijn_struct {
int i;
float f;
struct mijn_struct* next;
};

struct DS_struct_0 {
float a;
};

struct DS_struct_1 {
unsigned char a;
};

struct DS_struct_2 {
long a;
};

struct DS_struct_3 {
long a;
};

struct DS_struct_4 {
unsigned long a;
};

struct DS_struct_6 {
float a;
};

struct DS_struct_5 {
struct DS_struct_6 a;
};
// function declarations

void functie_voor_datastructuren(struct mijn_struct*);

char FF_function_48701(void);

char FF_function_48702(void);

char FF_function_48703(void);

char FF_function_48704(unsigned short, double, unsigned long long);

char FF_function_48705(void);

char FF_function_48706(long);

char FF_function_48707(unsigned char, float);

char FF_function_48708(long long, unsigned char, short);

char FF_function_48709(unsigned short, short, unsigned char);

char FF_function_48710(double, short, unsigned short);

char FF_function_48712(long long, ...);

long long FF_function_48714(struct mijn_struct, ...);

struct mijn_struct FF_function_48716(struct mijn_struct, ...);

long long FF_function_48721(struct mijn_struct, ...);

struct mijn_struct FF_function_48723(struct mijn_struct, ...);

unsigned long FF_function_48726(unsigned long long, ...);

struct DS_struct_1 FF_function_48738(long, ...);

struct DS_struct_1 FF_function_48746(struct DS_struct_0, ...);

struct mijn_struct FF_function_48750(short, ...);

double FF_function_48756(struct mijn_struct, ...);

struct mijn_struct FF_function_48757(long long, double);

char FF_function_48758(long long);

float FF_function_48759(long long, short, char);

double FF_function_48761(unsigned long, ...);

unsigned long FF_function_48763(long long, unsigned long, long);

unsigned long FF_function_48762(long long, unsigned char, unsigned long, long, char);

long long FF_function_48764(void);

unsigned char FF_function_48765(void);

unsigned long FF_function_48766(void);

long FF_function_48767(void);

char FF_function_48768(void);

unsigned long FF_function_48770(void);

unsigned long FF_function_48769(void);

unsigned long long FF_function_48772(void);

unsigned long long FF_function_48771(void);

double FF_function_48754(short, unsigned long long, float, float);

char FF_function_48774(void);

short FF_function_48776(void);

short FF_function_48775(void);

short FF_function_48773(void);

unsigned long long FF_function_48778(void);

unsigned long long FF_function_48780(void);

unsigned long long FF_function_48779(void);

unsigned long long FF_function_48777(void);

char FF_function_48782(void);

float FF_function_48784(unsigned char);

float FF_function_48783(void);

float FF_function_48781(unsigned char, long, long long, long);

unsigned char FF_function_48786(struct DS_struct_1, ...);

struct DS_struct_1 FF_function_48753(unsigned long long);

struct mijn_struct FF_function_48752(float, unsigned long long);

short FF_function_48751(long);

short FF_function_48748(unsigned long, long long, double, long, float, long);

struct DS_struct_0 FF_function_48747(float);

unsigned char FF_function_48744(unsigned short, float, unsigned short);

unsigned long FF_function_48743(long long, long long, char, char, unsigned short);

char FF_function_48742(unsigned long long);

long FF_function_48741(unsigned long long);

unsigned char FF_function_48740(long, unsigned char);

long FF_function_48739(unsigned long long);

char FF_function_48736(unsigned long long, unsigned long);

struct DS_struct_0 FF_function_48735(long, unsigned char, double, unsigned long, float, unsigned long, unsigned short);

struct mijn_struct FF_function_48734(unsigned short, long, float);

unsigned long long FF_function_48733(unsigned short, unsigned long long, double, long long, char, long, short, unsigned char);

char FF_function_48732(char, long long, short);

struct mijn_struct FF_function_48731(float, unsigned short);

long FF_function_48730(short, long, unsigned long);

struct DS_struct_0 FF_function_48729(unsigned long);

struct mijn_struct FF_function_48728(long long, double);

unsigned long long FF_function_48727(unsigned long long, short, long, unsigned long, long);

struct mijn_struct FF_function_48724(unsigned long, unsigned char);

struct mijn_struct FF_function_48719(char);

unsigned short FF_function_48718(unsigned long);

struct mijn_struct FF_function_48717(unsigned long long, long long, long long, unsigned long long, unsigned short, unsigned long long, float, double, float, unsigned char, double);

struct mijn_struct CF_function_48787(long long);

struct DS_struct_4 CF_function_48788(double);
// global variable declarations 

#pragma clang diagnostic ignored "-Wunused-value"

// global variables

// functions

void functie_voor_datastructuren(struct mijn_struct* ptr){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:functie_voor_datastructuren,AUTOGENERATED:T,ID:61209,CHECKSUM:B8BE");
	ptr->i = 0;
	ptr->f = 0;
	ptr->next = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:functie_voor_datastructuren,AUTOGENERATED:T,ID:6120a,CHECKSUM:98A7");
}
