#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

struct mijn_struct {
int i;
float f;
struct mijn_struct* next;
};

struct DS_struct_0 {
struct mijn_struct a;
};

struct DS_struct_1 {
struct mijn_struct a;
};

struct DS_struct_2 {
float a;
};

struct DS_struct_4 {
short a;
};

struct DS_struct_3 {
struct DS_struct_4 a;
};

struct DS_struct_5 {
long long a;
};
// function declarations

void functie_voor_datastructuren(struct mijn_struct*);

char FF_function_141324(short);

char FF_function_141325(float, long long, short, unsigned long long, unsigned long, char, unsigned long long, long);

char FF_function_141326(unsigned short, char);

char FF_function_141327(double);

char FF_function_141328(unsigned short);

char FF_function_141329(unsigned short);

char FF_function_141330(double, unsigned short);

char FF_function_141331(unsigned long long, long long, double, unsigned char, unsigned short, long, unsigned long long);

char FF_function_141332(long long);

char FF_function_141333(double, double, short);

char FF_function_141335(unsigned char, ...);

unsigned char FF_function_141337(float, ...);

float FF_function_141339(struct mijn_struct, ...);

char FF_function_141343(struct mijn_struct, ...);

struct mijn_struct FF_function_141345(struct mijn_struct, ...);

long FF_function_141348(struct mijn_struct, ...);

long FF_function_141352(long long, ...);

unsigned char FF_function_141361(struct mijn_struct, ...);

struct mijn_struct FF_function_141363(unsigned char, ...);

struct DS_struct_0 FF_function_141366(long, ...);

unsigned char FF_function_141374(unsigned long long, ...);

unsigned long long FF_function_141376(short, ...);

struct mijn_struct FF_function_141380(unsigned char, ...);

float FF_function_141384(unsigned long long, ...);

unsigned long long FF_function_141385(double, long, unsigned char, double, long, unsigned long long, double);

float FF_function_141386(void);

unsigned short FF_function_141387(void);

unsigned char FF_function_141389(void);

float FF_function_141390(void);

struct mijn_struct FF_function_141391(void);

struct mijn_struct FF_function_141388(void);

struct mijn_struct FF_function_141382(double);

struct mijn_struct FF_function_141393(void);

double FF_function_141394(void);

double FF_function_141392(void);

char FF_function_141397(void);

struct DS_struct_0 FF_function_141398(void);

double FF_function_141399(void);

long FF_function_141400(void);

long FF_function_141396(void);

long long FF_function_141402(void);

unsigned char FF_function_141404(unsigned short, ...);

unsigned short FF_function_141406(char, ...);

unsigned short FF_function_141408(float, ...);

unsigned char FF_function_141409(unsigned char);

unsigned char FF_function_141401(void);

unsigned char FF_function_141395(void);

unsigned char FF_function_141381(unsigned short);

unsigned short FF_function_141411(unsigned short, ...);

struct mijn_struct FF_function_141378(unsigned short, short);

short FF_function_141377(unsigned char, unsigned long long);

unsigned long FF_function_141372(double, double);

double FF_function_141371(char);

float FF_function_141370(short);

struct DS_struct_0 FF_function_141369(unsigned long, short);

struct DS_struct_0 FF_function_141368(unsigned long, long, unsigned long);

long FF_function_141367(unsigned long, long long);

unsigned char FF_function_141364(unsigned short, float, float, unsigned short, char);

struct mijn_struct FF_function_141359(long long, unsigned long long);

struct mijn_struct FF_function_141358(unsigned short, long);

unsigned char FF_function_141357(unsigned char);

unsigned long FF_function_141356(unsigned long, float, long long, long, short, float, char, unsigned long long);

struct mijn_struct FF_function_141355(double);

float FF_function_141354(long);

long long FF_function_141353(short, long long, long long, short, char);

char FF_function_141350(unsigned long, long long, double);

struct mijn_struct FF_function_141349(short, short, unsigned long, double, long, char, char);

struct mijn_struct FF_function_141346(unsigned long, unsigned long long);

struct mijn_struct FF_function_141341(float);

struct mijn_struct FF_function_141340(long, unsigned char, unsigned char, unsigned short, unsigned short);

struct DS_struct_1 CF_function_141412(float);
// global variable declarations 

#pragma clang diagnostic ignored "-Wunused-value"

// global variables

// functions

void functie_voor_datastructuren(struct mijn_struct* ptr){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:functie_voor_datastructuren,AUTOGENERATED:T,ID:1129f7,CHECKSUM:E391");
	ptr->i = 0;
	ptr->f = 0;
	ptr->next = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:functie_voor_datastructuren,AUTOGENERATED:T,ID:1129f8,CHECKSUM:ED0B");
}

char FF_function_141324(short p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_141324,AUTOGENERATED:T,ID:1129f9,CHECKSUM:B3EF");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141324,AUTOGENERATED:T,ID:1129fa,CHECKSUM:1825");
		return 0;
}

char FF_function_141325(float p0, long long p1, short p2, unsigned long long p3, unsigned long p4, char p5, unsigned long long p6, long p7){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_141325,AUTOGENERATED:T,ID:1129fb,CHECKSUM:CA50");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141325,AUTOGENERATED:T,ID:1129fc,CHECKSUM:5B5A");
		return 0;
}

char FF_function_141326(unsigned short p0, char p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_141326,AUTOGENERATED:T,ID:1129fd,CHECKSUM:0FD1");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141326,AUTOGENERATED:T,ID:1129fe,CHECKSUM:9EDB");
		return 0;
}

char FF_function_141327(double p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_141327,AUTOGENERATED:T,ID:1129ff,CHECKSUM:4CAE");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141327,AUTOGENERATED:T,ID:112a00,CHECKSUM:505B");
		return 0;
}

char FF_function_141328(unsigned short p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_141328,AUTOGENERATED:T,ID:112a01,CHECKSUM:DA51");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141328,AUTOGENERATED:T,ID:112a02,CHECKSUM:8ADA");
		return 0;
}

char FF_function_141329(unsigned short p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_141329,AUTOGENERATED:T,ID:112a03,CHECKSUM:992E");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141329,AUTOGENERATED:T,ID:112a04,CHECKSUM:0AA4");
		return 0;
}

char FF_function_141330(double p0, unsigned short p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_141330,AUTOGENERATED:T,ID:112a05,CHECKSUM:CEAC");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141330,AUTOGENERATED:T,ID:112a06,CHECKSUM:9E27");
		return 0;
}

char FF_function_141331(unsigned long long p0, long long p1, double p2, unsigned char p3, unsigned short p4, long p5, unsigned long long p6){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_141331,AUTOGENERATED:T,ID:112a07,CHECKSUM:8DD3");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141331,AUTOGENERATED:T,ID:112a08,CHECKSUM:D858");
		return 0;
}

char FF_function_141332(long long p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_141332,AUTOGENERATED:T,ID:112a09,CHECKSUM:8E53");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141332,AUTOGENERATED:T,ID:112a0a,CHECKSUM:2599");
		return 0;
}

char FF_function_141333(double p0, double p1, short p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:0,functionName:FF_function_141333,AUTOGENERATED:T,ID:112a0b,CHECKSUM:F7EC");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141333,AUTOGENERATED:T,ID:112a0c,CHECKSUM:66E6");
		return 0;
}

char FF_function_141335(unsigned char p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141335,AUTOGENERATED:T,ID:112a0d,CHECKSUM:3A3D");
	va_list va;
	va_start(va, p1);
	char first = __builtin_va_arg(va, char);
	va_end(va);
	FF_function_141335(0,1);
	FF_function_141335(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141335,AUTOGENERATED:T,ID:112a0e,CHECKSUM:AA67");
	return first;
}

unsigned char FF_function_141337(float p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141337,AUTOGENERATED:T,ID:112a0f,CHECKSUM:BE43");
	va_list va;
	va_start(va, p1);
	unsigned char first = __builtin_va_arg(va, unsigned char);
	va_end(va);
	FF_function_141337(0.0,1);
	FF_function_141337(0.0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141337,AUTOGENERATED:T,ID:112a10,CHECKSUM:4059");
	return first;
}

float FF_function_141339(struct mijn_struct p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141339,AUTOGENERATED:T,ID:112a11,CHECKSUM:49FD");
	va_list va;
	va_start(va, p1);
	float first = __builtin_va_arg(va, float);
	va_end(va);
	FF_function_141339((struct mijn_struct){0, 0.5, 0},1);
	FF_function_141339((struct mijn_struct){0, 0.5, 0},1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141339,AUTOGENERATED:T,ID:112a12,CHECKSUM:1826");
	return first;
}

char FF_function_141343(struct mijn_struct p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141343,AUTOGENERATED:T,ID:112a13,CHECKSUM:DA70");
	va_list va;
	va_start(va, p1);
	char first = __builtin_va_arg(va, char);
	va_end(va);
	FF_function_141343((struct mijn_struct){0, 0.5, 0},1);
	FF_function_141343((struct mijn_struct){0, 0.5, 0},1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141343,AUTOGENERATED:T,ID:112a14,CHECKSUM:48AA");
	return first;
}

struct mijn_struct FF_function_141345(struct mijn_struct p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141345,AUTOGENERATED:T,ID:112a15,CHECKSUM:16F1");
	va_list va;
	va_start(va, p1);
	struct mijn_struct first = __builtin_va_arg(va, struct mijn_struct);
	va_end(va);
	FF_function_141345((struct mijn_struct){0, 0.5, 0},1);
	FF_function_141345((struct mijn_struct){0, 0.5, 0},1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141345,AUTOGENERATED:T,ID:112a16,CHECKSUM:472A");
	return first;
}

long FF_function_141348(struct mijn_struct p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141348,AUTOGENERATED:T,ID:112a17,CHECKSUM:898F");
	va_list va;
	va_start(va, p1);
	long first = __builtin_va_arg(va, long);
	va_end(va);
	FF_function_141348((struct mijn_struct){0, 0.5, 0},1);
	FF_function_141348((struct mijn_struct){0, 0.5, 0},1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141348,AUTOGENERATED:T,ID:112a18,CHECKSUM:DD54");
	return first;
}

long FF_function_141352(long long p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141352,AUTOGENERATED:T,ID:112a19,CHECKSUM:DF0D");
	va_list va;
	va_start(va, p1);
	long first = __builtin_va_arg(va, long);
	va_end(va);
	FF_function_141352(0,1);
	FF_function_141352(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141352,AUTOGENERATED:T,ID:112a1a,CHECKSUM:7597");
	return first;
}

unsigned char FF_function_141361(struct mijn_struct p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141361,AUTOGENERATED:T,ID:112a1b,CHECKSUM:234B");
	va_list va;
	va_start(va, p1);
	unsigned char first = __builtin_va_arg(va, unsigned char);
	va_end(va);
	FF_function_141361((struct mijn_struct){0, 0.5, 0},1);
	FF_function_141361((struct mijn_struct){0, 0.5, 0},1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141361,AUTOGENERATED:T,ID:112a1c,CHECKSUM:B311");
	return first;
}

struct mijn_struct FF_function_141363(unsigned char p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141363,AUTOGENERATED:T,ID:112a1d,CHECKSUM:6434");
	va_list va;
	va_start(va, p1);
	struct mijn_struct first = __builtin_va_arg(va, struct mijn_struct);
	va_end(va);
	FF_function_141363(0,1);
	FF_function_141363(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141363,AUTOGENERATED:T,ID:112a1e,CHECKSUM:F46E");
	return first;
}

struct DS_struct_0 FF_function_141366(long p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141366,AUTOGENERATED:T,ID:112a1f,CHECKSUM:ACB5");
	va_list va;
	va_start(va, p1);
	struct DS_struct_0 first = __builtin_va_arg(va, struct DS_struct_0);
	va_end(va);
	FF_function_141366(0,1);
	FF_function_141366(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141366,AUTOGENERATED:T,ID:112a20,CHECKSUM:32AE");
	return first;
}

unsigned char FF_function_141374(unsigned long long p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141374,AUTOGENERATED:T,ID:112a21,CHECKSUM:6708");
	va_list va;
	va_start(va, p1);
	unsigned char first = __builtin_va_arg(va, unsigned char);
	va_end(va);
	FF_function_141374(0,1);
	FF_function_141374(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141374,AUTOGENERATED:T,ID:112a22,CHECKSUM:36D3");
	return first;
}

unsigned long long FF_function_141376(short p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141376,AUTOGENERATED:T,ID:112a23,CHECKSUM:E376");
	va_list va;
	va_start(va, p1);
	unsigned long long first = __builtin_va_arg(va, unsigned long long);
	va_end(va);
	FF_function_141376(0,1);
	FF_function_141376(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141376,AUTOGENERATED:T,ID:112a24,CHECKSUM:71AC");
	return first;
}

struct mijn_struct FF_function_141380(unsigned char p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141380,AUTOGENERATED:T,ID:112a25,CHECKSUM:2FEC");
	va_list va;
	va_start(va, p1);
	struct mijn_struct first = __builtin_va_arg(va, struct mijn_struct);
	va_end(va);
	FF_function_141380(0,1);
	FF_function_141380(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141380,AUTOGENERATED:T,ID:112a26,CHECKSUM:7E37");
	return first;
}

float FF_function_141384(unsigned long long p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141384,AUTOGENERATED:T,ID:112a27,CHECKSUM:6593");
	va_list va;
	va_start(va, p1);
	float first = __builtin_va_arg(va, float);
	va_end(va);
	FF_function_141384(0,1);
	FF_function_141384(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141384,AUTOGENERATED:T,ID:112a28,CHECKSUM:3148");
	return first;
}

unsigned long long FF_function_141385(double p0, long p1, unsigned char p2, double p3, long p4, unsigned long long p5, double p6){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141385,AUTOGENERATED:T,ID:112a29,CHECKSUM:23EC");
	(struct DS_struct_1){(struct mijn_struct){0, 0.5, 0}};
	if (rand() < 1) {
		return 0;
	}
	0;
	if (rand() < 1) {
		return 0;
	}
	0;
	if (rand() < 1) {
		return 0;
	}
	0;
	if (rand() < 1) {
		return 0;
	}
	0;
	if (rand() < 1) {
		return 0;
	}
	0;
	unsigned long long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141385,AUTOGENERATED:T,ID:112a2a,CHECKSUM:8976");
	return FF_x;
}

float FF_function_141386(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141386,AUTOGENERATED:T,ID:112a2b,CHECKSUM:1FAC");
	(struct DS_struct_0){(struct mijn_struct){0, 0.5, 0}};
	if (rand() < 1) {
		return 0.0;
	}
	(struct DS_struct_0){(struct mijn_struct){0, 0.5, 0}};
		return 0.0;
	0;
		return 0.0;
	0;
		return 0.0;
	(struct DS_struct_0){(struct mijn_struct){0, 0.5, 0}};
		return 0.0;
	(struct DS_struct_2){0.0};
	float FF_x = 0.0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141386,AUTOGENERATED:T,ID:112a2c,CHECKSUM:8FF6");
	return FF_x;
}

unsigned short FF_function_141387(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141387,AUTOGENERATED:T,ID:112a2d,CHECKSUM:9FD2");
	0;
		return 0;
	(struct DS_struct_1){(struct mijn_struct){0, 0.5, 0}};
		return 0;
	(struct DS_struct_1){(struct mijn_struct){0, 0.5, 0}};
	if (rand() < 1) {
		return 0;
	}
	0;
		return 0;
	(struct DS_struct_0){(struct mijn_struct){0, 0.5, 0}};
		return 0;
	(struct mijn_struct){0, 0.5, 0};
	unsigned short FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141387,AUTOGENERATED:T,ID:112a2e,CHECKSUM:0F88");
	return FF_x;
}

unsigned char FF_function_141389(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141389,AUTOGENERATED:T,ID:112a2f,CHECKSUM:C7AD");
	0;
		return 0;
	0;
		return 0;
	(struct DS_struct_2){0.0};
	unsigned char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141389,AUTOGENERATED:T,ID:112a30,CHECKSUM:39B7");
	return FF_x;
}

float FF_function_141390(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141390,AUTOGENERATED:T,ID:112a31,CHECKSUM:FCEF");
	0;
	float FF_x = 0.0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141390,AUTOGENERATED:T,ID:112a32,CHECKSUM:AD34");
	return FF_x;
}

struct mijn_struct FF_function_141391(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141391,AUTOGENERATED:T,ID:112a33,CHECKSUM:BF90");
	0;
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141391,AUTOGENERATED:T,ID:112a34,CHECKSUM:2D4A");
	return FF_x;
}

struct mijn_struct FF_function_141388(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141388,AUTOGENERATED:T,ID:112a35,CHECKSUM:E812");
	FF_function_141389();
		return (struct mijn_struct){0, 0.5, 0};
	FF_function_141390();
	struct mijn_struct FF_x = FF_function_141391();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141388,AUTOGENERATED:T,ID:112a36,CHECKSUM:B9C9");
	return FF_x;
}

struct mijn_struct FF_function_141382(double p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141382,AUTOGENERATED:T,ID:112a37,CHECKSUM:3B93");
	FF_function_141384(FF_function_141385(0.0, 0, 0, 0.0, 0, 0, 0.0), FF_function_141386(), FF_function_141387());
	struct mijn_struct FF_x = FF_function_141388();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141382,AUTOGENERATED:T,ID:112a38,CHECKSUM:6F48");
	return FF_x;
}

struct mijn_struct FF_function_141393(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141393,AUTOGENERATED:T,ID:112a39,CHECKSUM:FDEF");
	(struct DS_struct_0){(struct mijn_struct){0, 0.5, 0}};
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141393,AUTOGENERATED:T,ID:112a3a,CHECKSUM:5775");
	return FF_x;
}

double FF_function_141394(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141394,AUTOGENERATED:T,ID:112a3b,CHECKSUM:4A51");
	0;
	if (rand() < 1) {
		return 0.0;
	}
	(struct DS_struct_1){(struct mijn_struct){0, 0.5, 0}};
	double FF_x = 0.0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141394,AUTOGENERATED:T,ID:112a3c,CHECKSUM:DA0B");
	return FF_x;
}

double FF_function_141392(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141392,AUTOGENERATED:T,ID:112a3d,CHECKSUM:86D0");
	FF_function_141393();
	double FF_x = FF_function_141394();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141392,AUTOGENERATED:T,ID:112a3e,CHECKSUM:168A");
	return FF_x;
}

char FF_function_141397(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141397,AUTOGENERATED:T,ID:112a3f,CHECKSUM:4E51");
	(struct mijn_struct){0, 0.5, 0};
	if (rand() < 1) {
		return 0;
	}
	(struct DS_struct_0){(struct mijn_struct){0, 0.5, 0}};
		return 0;
	0.0;
	char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141397,AUTOGENERATED:T,ID:112a40,CHECKSUM:1048");
	return FF_x;
}

struct DS_struct_0 FF_function_141398(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141398,AUTOGENERATED:T,ID:112a41,CHECKSUM:9B12");
	(struct DS_struct_3){(struct DS_struct_4){0}};
	struct DS_struct_0 FF_x = (struct DS_struct_0){(struct mijn_struct){0, 0.5, 0}};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141398,AUTOGENERATED:T,ID:112a42,CHECKSUM:CAC9");
	return FF_x;
}

double FF_function_141399(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141399,AUTOGENERATED:T,ID:112a43,CHECKSUM:D86D");
	0;
		return 0.0;
	0;
	double FF_x = 0.0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141399,AUTOGENERATED:T,ID:112a44,CHECKSUM:4AB7");
	return FF_x;
}

long FF_function_141400(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141400,AUTOGENERATED:T,ID:112a45,CHECKSUM:CAB8");
	(struct DS_struct_0){(struct mijn_struct){0, 0.5, 0}};
	long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141400,AUTOGENERATED:T,ID:112a46,CHECKSUM:9B63");
	return FF_x;
}

long FF_function_141396(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141396,AUTOGENERATED:T,ID:112a47,CHECKSUM:006C");
	FF_function_141397();
		return 0;
	FF_function_141398();
		return 0;
	FF_function_141399();
	long FF_x = FF_function_141400();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141396,AUTOGENERATED:T,ID:112a48,CHECKSUM:54B7");
	return FF_x;
}

long long FF_function_141402(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141402,AUTOGENERATED:T,ID:112a49,CHECKSUM:8A47");
	(struct DS_struct_4){0};
		return 0;
	0;
	long long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141402,AUTOGENERATED:T,ID:112a4a,CHECKSUM:20DD");
	return FF_x;
}

unsigned char FF_function_141404(unsigned short p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141404,AUTOGENERATED:T,ID:112a4b,CHECKSUM:BF07");
	va_list va;
	va_start(va, p1);
	unsigned char first = __builtin_va_arg(va, unsigned char);
	va_end(va);
	FF_function_141404(0,1);
	FF_function_141404(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141404,AUTOGENERATED:T,ID:112a4c,CHECKSUM:2F5D");
	return first;
}

unsigned short FF_function_141406(char p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141406,AUTOGENERATED:T,ID:112a4d,CHECKSUM:F878");
	va_list va;
	va_start(va, p1);
	unsigned short first = __builtin_va_arg(va, unsigned short);
	va_end(va);
	FF_function_141406(0,1);
	FF_function_141406(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141406,AUTOGENERATED:T,ID:112a4e,CHECKSUM:6822");
	return first;
}

unsigned short FF_function_141408(float p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141408,AUTOGENERATED:T,ID:112a4f,CHECKSUM:A007");
	va_list va;
	va_start(va, p1);
	unsigned short first = __builtin_va_arg(va, unsigned short);
	va_end(va);
	FF_function_141408(0.0,1);
	FF_function_141408(0.0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141408,AUTOGENERATED:T,ID:112a50,CHECKSUM:5E1D");
	return first;
}

unsigned char FF_function_141409(unsigned char p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141409,AUTOGENERATED:T,ID:112a51,CHECKSUM:4CB9");
	0.0;
		return 0;
	(struct DS_struct_1){(struct mijn_struct){0, 0.5, 0}};
	unsigned char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141409,AUTOGENERATED:T,ID:112a52,CHECKSUM:1D62");
	return FF_x;
}

unsigned char FF_function_141401(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141401,AUTOGENERATED:T,ID:112a53,CHECKSUM:DAC7");
	FF_function_141402();
	unsigned char FF_x = FF_function_141404(FF_function_141406(0, 0, 0), FF_function_141408(0.0, 0, 0.0), FF_function_141409(0));
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141401,AUTOGENERATED:T,ID:112a54,CHECKSUM:481D");
	return FF_x;
}

unsigned char FF_function_141395(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141395,AUTOGENERATED:T,ID:112a55,CHECKSUM:96ED");
	FF_function_141396();
	unsigned char FF_x = FF_function_141401();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141395,AUTOGENERATED:T,ID:112a56,CHECKSUM:C736");
	return FF_x;
}

unsigned char FF_function_141381(unsigned short p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141381,AUTOGENERATED:T,ID:112a57,CHECKSUM:5C91");
	FF_function_141382(FF_function_141392());
	unsigned char FF_x = FF_function_141395();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141381,AUTOGENERATED:T,ID:112a58,CHECKSUM:084A");
	return FF_x;
}

unsigned short FF_function_141411(unsigned short p1, ...){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141411,AUTOGENERATED:T,ID:112a59,CHECKSUM:5D44");
	va_list va;
	va_start(va, p1);
	unsigned short first = __builtin_va_arg(va, unsigned short);
	va_end(va);
	FF_function_141411(0,1);
	FF_function_141411(0,1,2,3);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141411,AUTOGENERATED:T,ID:112a5a,CHECKSUM:F7DE");
	return first;
}

struct mijn_struct FF_function_141378(unsigned short p0, short p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141378,AUTOGENERATED:T,ID:112a5b,CHECKSUM:B64B");
	FF_function_141380(FF_function_141381(FF_function_141411(0, 0, 0)), 0, 0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141378,AUTOGENERATED:T,ID:112a5c,CHECKSUM:2611");
	return FF_x;
}

short FF_function_141377(unsigned char p0, unsigned long long p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141377,AUTOGENERATED:T,ID:112a5d,CHECKSUM:AFCB");
	FF_function_141378(0, 0);
		return 0;
	0;
	short FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141377,AUTOGENERATED:T,ID:112a5e,CHECKSUM:3F91");
	return FF_x;
}

unsigned long FF_function_141372(double p0, double p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141372,AUTOGENERATED:T,ID:112a5f,CHECKSUM:674A");
	FF_function_141374(FF_function_141376(FF_function_141377(0, 0), 0, 0), 0, 0.0);
	unsigned long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141372,AUTOGENERATED:T,ID:112a60,CHECKSUM:F951");
	return FF_x;
}

double FF_function_141371(char p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141371,AUTOGENERATED:T,ID:112a61,CHECKSUM:AE0A");
	FF_function_141372(0.0, 0.0);
	double FF_x = 0.0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141371,AUTOGENERATED:T,ID:112a62,CHECKSUM:FFD1");
	return FF_x;
}

float FF_function_141370(short p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141370,AUTOGENERATED:T,ID:112a63,CHECKSUM:ED75");
	FF_function_141371(0);
		return 0.0;
	0;
		return 0.0;
	(struct DS_struct_1){(struct mijn_struct){0, 0.5, 0}};
	float FF_x = 0.0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141370,AUTOGENERATED:T,ID:112a64,CHECKSUM:7FAF");
	return FF_x;
}

struct DS_struct_0 FF_function_141369(unsigned long p0, short p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141369,AUTOGENERATED:T,ID:112a65,CHECKSUM:BAF7");
	FF_function_141370(0);
	struct DS_struct_0 FF_x = (struct DS_struct_0){(struct mijn_struct){0, 0.5, 0}};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141369,AUTOGENERATED:T,ID:112a66,CHECKSUM:EB2C");
	return FF_x;
}

struct DS_struct_0 FF_function_141368(unsigned long p0, long p1, unsigned long p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141368,AUTOGENERATED:T,ID:112a67,CHECKSUM:F988");
	FF_function_141369(0, 0);
	struct DS_struct_0 FF_x = (struct DS_struct_0){(struct mijn_struct){0, 0.5, 0}};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141368,AUTOGENERATED:T,ID:112a68,CHECKSUM:AD53");
	return FF_x;
}

long FF_function_141367(unsigned long p0, long long p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141367,AUTOGENERATED:T,ID:112a69,CHECKSUM:2609");
	FF_function_141368(0, 0, 0);
	long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141367,AUTOGENERATED:T,ID:112a6a,CHECKSUM:8C93");
	return FF_x;
}

unsigned char FF_function_141364(unsigned short p0, float p1, float p2, unsigned short p3, char p4){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141364,AUTOGENERATED:T,ID:112a6b,CHECKSUM:1A49");
	FF_function_141366(FF_function_141367(0, 0), 0, 0);
	unsigned char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141364,AUTOGENERATED:T,ID:112a6c,CHECKSUM:8A13");
	return FF_x;
}

struct mijn_struct FF_function_141359(long long p0, unsigned long long p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141359,AUTOGENERATED:T,ID:112a6d,CHECKSUM:8630");
	FF_function_141361(FF_function_141363(FF_function_141364(0, 0.0, 0.0, 0, 0), 0, 0), 0, 0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141359,AUTOGENERATED:T,ID:112a6e,CHECKSUM:166A");
	return FF_x;
}

struct mijn_struct FF_function_141358(unsigned short p0, long p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141358,AUTOGENERATED:T,ID:112a6f,CHECKSUM:C54F");
	FF_function_141359(0, 0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141358,AUTOGENERATED:T,ID:112a70,CHECKSUM:3B55");
	return FF_x;
}

unsigned char FF_function_141357(unsigned char p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141357,AUTOGENERATED:T,ID:112a71,CHECKSUM:B00F");
	FF_function_141358(0, 0);
	unsigned char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141357,AUTOGENERATED:T,ID:112a72,CHECKSUM:E1D4");
	return FF_x;
}

unsigned long FF_function_141356(unsigned long p0, float p1, long long p2, long p3, short p4, float p5, char p6, unsigned long long p7){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141356,AUTOGENERATED:T,ID:112a73,CHECKSUM:F370");
	FF_function_141357(0);
	unsigned long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141356,AUTOGENERATED:T,ID:112a74,CHECKSUM:61AA");
	return FF_x;
}

struct mijn_struct FF_function_141355(double p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141355,AUTOGENERATED:T,ID:112a75,CHECKSUM:36F1");
	FF_function_141356(0, 0.0, 0, 0, 0, 0.0, 0, 0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141355,AUTOGENERATED:T,ID:112a76,CHECKSUM:672A");
	return FF_x;
}

float FF_function_141354(long p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141354,AUTOGENERATED:T,ID:112a77,CHECKSUM:758E");
	FF_function_141355(0.0);
	float FF_x = 0.0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141354,AUTOGENERATED:T,ID:112a78,CHECKSUM:2155");
	return FF_x;
}

long long FF_function_141353(short p0, long long p1, long long p2, short p3, char p4){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141353,AUTOGENERATED:T,ID:112a79,CHECKSUM:FDF0");
	FF_function_141354(0);
	long long FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141353,AUTOGENERATED:T,ID:112a7a,CHECKSUM:576A");
	return FF_x;
}

char FF_function_141350(unsigned long p0, long long p1, double p2){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141350,AUTOGENERATED:T,ID:112a7b,CHECKSUM:C1B0");
	FF_function_141352(FF_function_141353(0, 0, 0, 0, 0), 0, 0.0);
	char FF_x = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141350,AUTOGENERATED:T,ID:112a7c,CHECKSUM:51EA");
	return FF_x;
}

struct mijn_struct FF_function_141349(short p0, short p1, unsigned long p2, double p3, long p4, char p5, char p6){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141349,AUTOGENERATED:T,ID:112a7d,CHECKSUM:9632");
	FF_function_141350(0, 0, 0.0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141349,AUTOGENERATED:T,ID:112a7e,CHECKSUM:0668");
	return FF_x;
}

struct mijn_struct FF_function_141346(unsigned long p0, unsigned long long p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141346,AUTOGENERATED:T,ID:112a7f,CHECKSUM:4CB3");
	FF_function_141348(FF_function_141349(0, 0, 0, 0.0, 0, 0, 0), 0, 0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141346,AUTOGENERATED:T,ID:112a80,CHECKSUM:D2AD");
	return FF_x;
}

struct mijn_struct FF_function_141341(float p0){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141341,AUTOGENERATED:T,ID:112a81,CHECKSUM:0E08");
	FF_function_141343(FF_function_141345(FF_function_141346(0, 0), 0, 0), 0, 0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141341,AUTOGENERATED:T,ID:112a82,CHECKSUM:5FD3");
	return FF_x;
}

struct mijn_struct FF_function_141340(long p0, unsigned char p1, unsigned char p2, unsigned short p3, unsigned short p4){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:FF_function_141340,AUTOGENERATED:T,ID:112a83,CHECKSUM:4D77");
	FF_function_141341(0.0);
	struct mijn_struct FF_x = (struct mijn_struct){0, 0.5, 0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:FF_function_141340,AUTOGENERATED:T,ID:112a84,CHECKSUM:DFAD");
	return FF_x;
}

struct DS_struct_1 CF_function_141412(float p1){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:CF_function_141412,AUTOGENERATED:T,ID:112a85,CHECKSUM:5987");
	/* I/F TYPE    N/U IN UP TS  IC IE  EB EE ER ED EN EF  LV VT LU LT */
	/* PFL DOWHILE --  F  F  F   T  T   F  T  F  T  F  F   F           */
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:266666,PLID:-1,loopcom:DOWHILE,IGE:T,NESTLEV:0,ICC:T,UNR:NU,finitude:PFL,EEX:T,location:BEFORE,ID:1129f1,EGA:T,CHECKSUM:33B4");
	/* no loop var used, so no init */
	do {
		printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:266666,location:BODY,ID:1129f2,CHECKSUM:1A37");
		printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:266666,location:UNDEFINED,ID:1129f3,DUMMY:T,CHECKSUM:EB41");
		if (getchar()==97) {exit(1923);}
		if (getchar()==19) {goto _LAB1;} // goto directly after
		FF_function_141371(0);
		if (getchar()==67) {continue;}
		if (getchar()==17) {goto _LAB0;} // goto end of loop body
		printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:266666,location:UNDEFINED,ID:1129f4,DUMMY:T,CHECKSUM:DB67");
		_LAB0:
		;
	} while (true);
	_LAB1:
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:266666,location:AFTER,ID:1129f5,CHECKSUM:3F9F");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>LOOPID:266666,location:UNDEFINED,ID:1129f6,DUMMY:T,CHECKSUM:BB7E");
	_LAB2:
	;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:CF_function_141412,AUTOGENERATED:T,ID:112a86,CHECKSUM:085C");
	return (struct DS_struct_1){(struct mijn_struct){0, 0.5, 0}};
}

int main(void){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:main,AUTOGENERATED:T,ID:112a87,CHECKSUM:93D0");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8MD>>ID:1129e3,version:1.0.0,CHECKSUM:642C");
	struct mijn_struct* my_instance;
	functie_voor_datastructuren(my_instance);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129e4,CHECKSUM:DB60");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129e5,CHECKSUM:1BA1");
	FF_function_141335(FF_function_141337(FF_function_141339(FF_function_141340(0, 0, 0, 0, 0), 0, 0), 0, 0.0), 0.0, 0);
	(struct DS_struct_0){(struct mijn_struct){0, 0.5, 0}};
	FF_function_141367(0, 0);
	0;
	0;
	FF_function_141400();
	(struct DS_struct_0){(struct mijn_struct){0, 0.5, 0}};
	0.0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129e6,CHECKSUM:1AE1");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129e7,CHECKSUM:DA20");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129e8,CHECKSUM:DE60");
	FF_function_141352(FF_function_141353(0, 0, 0, 0, FF_function_141343((struct mijn_struct){0, 0.5, 0}, 0, 0.0)));
	0;
	0.0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129e9,CHECKSUM:1EA1");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129ea,CHECKSUM:E4A0");
	(struct DS_struct_5){0};
	(struct DS_struct_5){0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129eb,CHECKSUM:E5E0");
	FF_function_141401();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129ec,CHECKSUM:2521");
	0.0;
	0;
	(struct DS_struct_5){0};
	FF_function_141397();
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129ed,CHECKSUM:E760");
	(struct DS_struct_2){0.0};
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129ee,CHECKSUM:27A1");
	0.0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129ef,CHECKSUM:26E1");
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8CF>>ID:1129f0,CHECKSUM:E861");
	CF_function_141412(0.0);
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:main,AUTOGENERATED:T,ID:112a88,CHECKSUM:BE69");
	return 0;
}
