#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

struct mijn_struct {
int i;
float f;
struct mijn_struct* next;
};

struct DS_struct_0 {
struct mijn_struct a;
};

struct DS_struct_1 {
struct mijn_struct a;
};

struct DS_struct_2 {
float a;
};

struct DS_struct_4 {
short a;
};

struct DS_struct_3 {
struct DS_struct_4 a;
};

struct DS_struct_5 {
long long a;
};
// function declarations

void functie_voor_datastructuren(struct mijn_struct*);

char FF_function_141324(short);

char FF_function_141325(float, long long, short, unsigned long long, unsigned long, char, unsigned long long, long);

char FF_function_141326(unsigned short, char);

char FF_function_141327(double);

char FF_function_141328(unsigned short);

char FF_function_141329(unsigned short);

char FF_function_141330(double, unsigned short);

char FF_function_141331(unsigned long long, long long, double, unsigned char, unsigned short, long, unsigned long long);

char FF_function_141332(long long);

char FF_function_141333(double, double, short);

char FF_function_141335(unsigned char, ...);

unsigned char FF_function_141337(float, ...);

float FF_function_141339(struct mijn_struct, ...);

char FF_function_141343(struct mijn_struct, ...);

struct mijn_struct FF_function_141345(struct mijn_struct, ...);

long FF_function_141348(struct mijn_struct, ...);

long FF_function_141352(long long, ...);

unsigned char FF_function_141361(struct mijn_struct, ...);

struct mijn_struct FF_function_141363(unsigned char, ...);

struct DS_struct_0 FF_function_141366(long, ...);

unsigned char FF_function_141374(unsigned long long, ...);

unsigned long long FF_function_141376(short, ...);

struct mijn_struct FF_function_141380(unsigned char, ...);

float FF_function_141384(unsigned long long, ...);

unsigned long long FF_function_141385(double, long, unsigned char, double, long, unsigned long long, double);

float FF_function_141386(void);

unsigned short FF_function_141387(void);

unsigned char FF_function_141389(void);

float FF_function_141390(void);

struct mijn_struct FF_function_141391(void);

struct mijn_struct FF_function_141388(void);

struct mijn_struct FF_function_141382(double);

struct mijn_struct FF_function_141393(void);

double FF_function_141394(void);

double FF_function_141392(void);

char FF_function_141397(void);

struct DS_struct_0 FF_function_141398(void);

double FF_function_141399(void);

long FF_function_141400(void);

long FF_function_141396(void);

long long FF_function_141402(void);

unsigned char FF_function_141404(unsigned short, ...);

unsigned short FF_function_141406(char, ...);

unsigned short FF_function_141408(float, ...);

unsigned char FF_function_141409(unsigned char);

unsigned char FF_function_141401(void);

unsigned char FF_function_141395(void);

unsigned char FF_function_141381(unsigned short);

unsigned short FF_function_141411(unsigned short, ...);

struct mijn_struct FF_function_141378(unsigned short, short);

short FF_function_141377(unsigned char, unsigned long long);

unsigned long FF_function_141372(double, double);

double FF_function_141371(char);

float FF_function_141370(short);

struct DS_struct_0 FF_function_141369(unsigned long, short);

struct DS_struct_0 FF_function_141368(unsigned long, long, unsigned long);

long FF_function_141367(unsigned long, long long);

unsigned char FF_function_141364(unsigned short, float, float, unsigned short, char);

struct mijn_struct FF_function_141359(long long, unsigned long long);

struct mijn_struct FF_function_141358(unsigned short, long);

unsigned char FF_function_141357(unsigned char);

unsigned long FF_function_141356(unsigned long, float, long long, long, short, float, char, unsigned long long);

struct mijn_struct FF_function_141355(double);

float FF_function_141354(long);

long long FF_function_141353(short, long long, long long, short, char);

char FF_function_141350(unsigned long, long long, double);

struct mijn_struct FF_function_141349(short, short, unsigned long, double, long, char, char);

struct mijn_struct FF_function_141346(unsigned long, unsigned long long);

struct mijn_struct FF_function_141341(float);

struct mijn_struct FF_function_141340(long, unsigned char, unsigned char, unsigned short, unsigned short);

struct DS_struct_1 CF_function_141412(float);
// global variable declarations 

#pragma clang diagnostic ignored "-Wunused-value"

// global variables

// functions

void functie_voor_datastructuren(struct mijn_struct* ptr){
printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>callable:1,functionName:functie_voor_datastructuren,AUTOGENERATED:T,ID:1129f7,CHECKSUM:E391");
	ptr->i = 0;
	ptr->f = 0;
	ptr->next = 0;
	printf("c5852db2-7acb-cba3-7f81-e7ef3cd1d3b8FF>>functionName:functie_voor_datastructuren,AUTOGENERATED:T,ID:1129f8,CHECKSUM:ED0B");
}
